Feature/droits acces
ETICINSATechnologies/Keros-Back pull request #102
Opened 2019-06-26 20:40 UTC by Arteox

rebase fini

2019-06-26 21:12 UTC, PaulGOUX27 requested changes
2 petits changements, presque rien.
Il y a le fichier ` tests/test.txt` à supprimer aussi 😉

2019-06-26 21:12 UTC, PaulGOUX27 commented on src/Services/Auth/AccessRightsService.php
> +    public function checkRightsPostMember(Request $request)
Peut être changer en `checkRightsCreateMember`, le post est utilisé pour le create et l'update

2019-06-26 21:12 UTC, PaulGOUX27 commented on src/Tools/Validator.php
> +    public static function requiredMember($member) : Member
Elle est utilisée ? Parce que je pense que ça vérifie juste que `$member` est pas vide, ou non null ... la gestion des vraix/faux en PHP est très spécial par rapport aux chaines vides, entier 0 ... Donc si on l'utilise pas autant l'enlever

Voir [ici](https://stackoverflow.com/a/15607549/8826506)
et [ici](https://stackoverflow.com/a/2382510/8826506)

2019-06-26 21:17 UTC, Arteox commented on src/Services/Auth/AccessRightsService.php
> +    public function checkRightsPostMember(Request $request)
Fait

2019-06-26 21:20 UTC, Arteox commented on src/Tools/Validator.php
> +    public static function requiredMember($member) : Member
En effet c'est pas utilisé je l'enlève et je viens d'apprendre des trucs sur PHP je savais pas merci ^^

2019-06-26 21:51 UTC, PaulGOUX27 approved these changes

2019-07-09 17:18 UTC, ConorRyan commented on src/KerosApp.php
> +        $this->memberService=($app->getContainer())->get(MemberService::class);
Tu set $memberService mais ce n'est jamasi utilisé, je pense qu'il faut supprimer l'attribut, cette ligne, et l'import non ?.

2019-07-09 17:18 UTC, ConorRyan commented on src/Services/Auth/AccessRightsService.php
> +        $accessAllowed = array(19, 22); //resp RH et secrétaire général
Je pense que ça vaudrait le coup de setter des attributs constants (publics encore mieux pour être utilisé autre part), genre :
``` 
RESP_RH_ID = 19;
SECRETAIRE_GENERALE_ID = 50
```
et puis utiliser ces constantes dans le code pour être plus lisible

2019-07-09 17:18 UTC, ConorRyan commented on src/Services/Auth/AccessRightsService.php
> +        $accessAllowed = array(19, 22); //resp RH et secrétaire général
Idem pour les autres en dessous :)

2019-07-09 17:48 UTC, Arteox commented on src/KerosApp.php
> +        $this->memberService=($app->getContainer())->get(MemberService::class);
Yes t'as raison il doit venir d'un rebase j'ai oublié de l'enlever

2019-07-09 17:59 UTC, Arteox commented on src/Services/Auth/AccessRightsService.php
> +        $accessAllowed = array(19, 22); //resp RH et secrétaire général
Bonne idée !

2019-07-09 19:23 UTC, ConorRyan requested changes

2019-07-09 19:23 UTC, ConorRyan commented on src/Services/Auth/AccessRightsService.php
> +        $accessAllowed = array(21); //resp UA
self::UA_MANAGER_ID

2019-07-09 20:19 UTC, ConorRyan approved these changes

2019-07-09 20:19 UTC, merged