Test/delete all member
ETICINSATechnologies/Keros-Back pull request #118
Opened 2019-08-18 21:10 UTC by PaulGOUX27

Test sur la suppression des membres. On en supprime 25, en considérant que ça test tous les cas.

J'ai tenté de tous, les supprimer, mais j'ai une erreur étrange 👇 
![image](https://user-images.githubusercontent.com/32762729/63230461-2dc8ab80-c20d-11e9-88ce-94144d2187e7.png)
J'ai bien vérifié, mais je comprend pas. Après, je pense qu'on peut considérer qu'avec 25 delete c'est suffissant.

2019-08-19 17:18 UTC, PaulGOUX27 commented
merci Sad ❤️

2019-08-25 09:44 UTC, Arteox requested changes
Juste un commentaire à supprimer

2019-08-25 09:44 UTC, Arteox commented on src/DataServices/Core/MemberDataService.php
> +            //$this->logger->debug($this->queryBuilder);
Ligne à supprimer

2019-08-25 09:57 UTC, PaulGOUX27 commented on src/DataServices/Core/MemberDataService.php
> +            //$this->logger->debug($this->queryBuilder);
done ;)

2019-08-25 10:04 UTC, Arteox approved these changes

2019-08-25 11:30 UTC, merged