Feature/access rights
ETICINSATechnologies/Keros-Back pull request #134
Opened 2019-10-20 17:40 UTC by teckwan

2019-10-20 20:03 UTC, PaulGOUX27 requested changes
Super le coup pour mettre le droit d'accès sur un groupe entier.

2019-10-20 20:03 UTC, PaulGOUX27 commented on src/Services/Auth/AccessRightsService.php
> +    public function checkRightsMemberAccess(Request $request, Response $response, callable $next)
Je mettrais plutôt `checkRightNotAlumni`, c'est plus explicite

2019-10-20 20:03 UTC, PaulGOUX27 commented on src/Services/Auth/AccessRightsService.php
> +        }
Pourquoi le try ?

2019-10-20 20:23 UTC, teckwan commented on src/Services/Auth/AccessRightsService.php
> +        }
parce que si c'est un consultant qui accède le getOne de memberService va échouer et ça throw

2019-10-21 07:56 UTC, PaulGOUX27 commented on src/Services/Auth/AccessRightsService.php
> +        }
ça veut dire que si c'est un consultant qui accède à la route, `isAlumni` est false et il se prend une exception non ?

2019-10-21 12:44 UTC, teckwan commented on src/Services/Auth/AccessRightsService.php
> +        }
justement si c'est un consultant on veut le laisser passer aussi non? c'est pour ça que je fais un catch sur l'exception pour le laisser passer

2019-10-21 14:23 UTC, PaulGOUX27 commented on src/Services/Auth/AccessRightsService.php
> +        }
oui, mais si c'est un consultant, au début `isAlumni` est faux, tu rentre dans le try, et le `getOne` lève une exception (car c'est un consultant). Ensuite, `isAlumni` est  faux, donc tu lève une exception comme quoi l'accès est interdit.

Ça fait bien ça non ?

2019-10-21 16:02 UTC, PaulGOUX27 approved these changes

2019-10-21 16:02 UTC, merged