fix orderBy member
ETICINSATechnologies/Keros-Back pull request #140
Opened 2019-12-12 18:14 UTC by PaulGOUX27

Fix les order by pour les members.
L'order by sur les pole fonctionne bizarrement (member>position>pole, position pouvant être vide et pole pouvant être null)

2019-12-16 18:19 UTC, OrcaZ969 commented on src/DataServices/Core/MemberDataService.php
>              }
m, u, p are the abbreviations of member username and positionLabel in the sql query.

2019-12-16 18:20 UTC, OrcaZ969 approved these changes

2019-12-19 15:23 UTC, slokuge requested changes
Need to implement the same services for member inscriptions

2019-12-20 14:06 UTC, PaulGOUX27 commented
MemberInscription use Criteria from Doctrine, and it already works well. I have fix same issue on Consultant.

2019-12-21 14:25 UTC, slokuge approved these changes
Good for me

2019-12-22 14:02 UTC, merged