Feature/reset password
ETICINSATechnologies/Keros-Back pull request #148
Opened 2020-02-12 17:32 UTC by neeeekitos

2020-02-13 09:21 UTC, PaulGOUX27 requested changes

2020-02-13 09:21 UTC, PaulGOUX27 commented on src/DataServices/Core/MemberDataService.php
> +            $this->logger->debug($email);
Un petit log qui est resté

2020-02-13 09:21 UTC, PaulGOUX27 commented on src/Services/Core/MemberService.php
> +
Tu peux éviter tout ce if en enlevant juste le ? dans les paramètres de la fonction

2020-02-13 09:21 UTC, PaulGOUX27 commented on src/Services/Core/MemberService.php
> +            throw new KerosException("token wasn't found", 401);
Plus un 403 je pense (idem en dessous) https://en.wikipedia.org/wiki/List_of_HTTP_status_codes

2020-02-13 09:21 UTC, PaulGOUX27 commented on src/Tools/Mail/MailFactory.php
> +        $tos = array("nekit.morj@gmail.com" => array(
C'est ton adresse mail en dur là 😄

2020-02-13 09:21 UTC, PaulGOUX27 commented on src/Tools/Mail/MailFactory.php
> +          //"identifiant"=>$member->getUser()->getUsername(),
tu peux enlever le commentaire

2020-02-13 09:21 UTC, PaulGOUX27 commented on src/Tools/Mail/MailSender.php
> +        $this->logger->debug($response->statusCode());
Petit log de trop

2020-02-13 09:21 UTC, PaulGOUX27 commented on src/KerosApp.php
> +                    $this->post("/reset-password", MemberController::class . ':postResetPassword');
Tu n'utilise pas cet endpoint (pas de fonction associée dans le memberControler)

2020-02-15 21:19 UTC, PaulGOUX27 requested changes
Oupsi, j'ai pas bien fait gaffe à qlq truc la fois d'avant 😅

2020-02-15 21:19 UTC, PaulGOUX27 commented on src/Services/Core/MemberService.php
> +            throw new KerosException("token wasn't found", 403);
404

2020-02-15 21:19 UTC, PaulGOUX27 commented on src/Services/Core/MemberService.php
> +            throw new KerosException("User doesn't exist", 401);
404

2020-02-15 21:19 UTC, PaulGOUX27 commented on src/Services/Core/MemberService.php
> +            throw new KerosException("Reset MP token has expired, please reset again", 401);
403

2020-02-15 21:19 UTC, PaulGOUX27 commented on src/Services/Core/MemberService.php
> +        return $fields;
tu peux return juste l'id, c'est un peu plus simple comme ça

2020-02-15 21:19 UTC, PaulGOUX27 commented on src/Controllers/Auth/LoginController.php
> +    }
`return $response->withStatus(200);`

2020-02-15 21:19 UTC, PaulGOUX27 commented on src/Controllers/Auth/LoginController.php
> +        $param = $request->getQueryParams();
Je pense qu'il faut aussi mettre le token dans le body, et pas dans les query params. Dans le mail il est dans le params, mais rien n'empêche le front de nous le repasser via le body. Les query param sont plus utilisé pour filtrer les résultats

2020-02-17 07:06 UTC, neeeekitos commented on src/Controllers/Auth/LoginController.php
> +        $param = $request->getQueryParams();
aa donc c'est une convention? ( que query param est que pour l'affichage et le tri)

2020-02-17 07:52 UTC, PaulGOUX27 commented on src/Controllers/Auth/LoginController.php
> +        $param = $request->getQueryParams();
Oui tout à fait, comme les status code et les méthodes HTTP (GET, POST, PUT ...)

2020-02-17 07:56 UTC, PaulGOUX27 requested changes
Je viens de penser à autre chose : il faut aussi ajouter les clé API (ici `MAIL_RESET_MP_TOKEN_ENVOIE = d-da0e15b4bfdf4aefa705b939dc4bdc00`) dans les 2 autres fichiers .ini (dans le dossier .deploy)

2020-02-17 19:37 UTC, PaulGOUX27 approved these changes

2020-02-17 20:14 UTC, merged