Feature/export csv
ETICINSATechnologies/Keros-Back pull request #151
Opened 2020-02-20 07:56 UTC by teckwan

Implemented csv export for members.

2020-02-20 09:21 UTC, PaulGOUX27 requested changes
Pas mal de chose à revoir, mais j'aime beaucoup la manière dont tu l'as fait 👍

2020-02-20 09:21 UTC, PaulGOUX27 commented on src/Controllers/Core/MemberController.php
> +		rewind($csvFile);
A mettre dans un service, de manière général dans les controller on gère la requête et sa réponse, l'appel d'un service ou l'orchestration de plusieurs services

2020-02-20 09:21 UTC, PaulGOUX27 commented on src/KerosApp.php
> +					$this->post("/export", MemberController::class . ':exportMembers');
Une raison particulière au POST ? Parce que j'aurais mis du GET

2020-02-20 09:21 UTC, PaulGOUX27 commented on src/Controllers/Core/MemberController.php
> +		$members = $this->memberService->getSome($body["idList"]);
Vérifier que le "idList" existe (isset), sinon ça donne une erreur bizarre

2020-02-20 09:21 UTC, PaulGOUX27 commented on src/Controllers/Core/MemberController.php
> +		return $response->withBody(new \Slim\Http\Stream($csvFile));
Quand on retourne un document, on retourne un path vers ce document, de la forme suivante : 
![image](https://user-images.githubusercontent.com/32762729/74917836-7170bd80-53c8-11ea-8efc-894791deafcf.png)
Un exemple de code (MemberInscriptionController) : 
![image](https://user-images.githubusercontent.com/32762729/74918037-cdd3dd00-53c8-11ea-9f48-7120bdfd4b97.png)
L'idée est de mettre le document dans `documents/tmp` qui est un dossier accessible depuis l'extérieur, et ne pas renvoyer le fichier dans la requête (si il est trop gros, ça peux le couper, même si dans ton cas je pense que ça fonctionne bien). C'est sourtout pour garder un fonctionnement similaire avec le front, et pour eux c'est plus simple je pense de reçevoir une url que le fichier en lui même

2020-02-20 09:21 UTC, PaulGOUX27 commented on src/Controllers/Core/MemberController.php
> +							}
Vu que tu les tris mtn, le if te sret plus non ? la première position de la liste est la plus récente non ?

2020-02-20 09:21 UTC, PaulGOUX27 commented on src/Controllers/Core/MemberController.php
> +									$poles[$position->getPosition()->getPole()->getName()] = null;
C'est un peu bizarre, mais en effet je sais pas si y'a moyen d'ajouter dans un tableau sans les index en php.
Tu peux close le commentaire 😉

2020-02-20 09:21 UTC, PaulGOUX27 commented on src/Controllers/Core/MemberController.php
> +						if (count($poles)) {
`if (count($poles) > 0)` pour être plus facilement compréhensible 😄

2020-02-20 09:23 UTC, PaulGOUX27 commented
J'ai testé quelque cas un peu merdique (une virgule dans le champs, un id qui existe pas) et ça fonctionne nikel 😉

2020-02-20 10:49 UTC, teckwan commented on src/Controllers/Core/MemberController.php
> +									$poles[$position->getPosition()->getPole()->getName()] = null;
c'est surtout pour avoir le comportement d'un set en fait, vu que php n'a pas de set

2020-02-20 11:19 UTC, PaulGOUX27 commented on src/Controllers/Core/MemberController.php
> +									$poles[$position->getPosition()->getPole()->getName()] = null;
smart mdr

2020-02-22 14:08 UTC, PaulGOUX27 commented on src/Controllers/Core/MemberController.php
> +		$location = $this->memberService->export($request->getQueryParam('idList'));
Y'a une raison spécifique au fait que tu demande les ids via les query params et plus le body ?
Je dit ça principalement parce que ça me semble bien clair pour passer un array en param (je sais pas comment s'écrit la rq). 
De ce que je vois au premier abord c'est pas si simple 😅 https://stackoverflow.com/questions/6243051/how-to-pass-an-array-within-a-query-string

2020-02-22 14:47 UTC, teckwan commented on src/Controllers/Core/MemberController.php
> +		$location = $this->memberService->export($request->getQueryParam('idList'));
du coup vu que c'est un GET je me suis dit que c'est pas ouf d'avoir un body, c'est pour ça que je suis parti pour un POST.. mais si tu veux oui on peut faire un GET avec body

2020-02-22 15:14 UTC, PaulGOUX27 commented on src/Controllers/Core/MemberController.php
> +		$location = $this->memberService->export($request->getQueryParam('idList'));
tu peux me montrer à quoi ressemble la requête dans la manière dont tu l'as fait stp ? 😄

2020-02-22 15:38 UTC, teckwan commented on src/Controllers/Core/MemberController.php
> +		$location = $this->memberService->export($request->getQueryParam('idList'));
![pic-full-200222-1637-38](https://user-images.githubusercontent.com/36706647/75095086-cad81880-5591-11ea-9d76-59997f7a2c2a.png)

2020-02-27 13:36 UTC, PaulGOUX27 requested changes

2020-02-27 13:36 UTC, PaulGOUX27 commented on src/Services/Core/MemberService.php
> +						$latestYear = $memberData[$value][0]->getYear();
Si le membre a pas de position ça plante 
`[2020-02-27 13:18:07] Keros.ERROR: File : C:\Users\Paul\Documents\Keros-Back\src\Services\Core\MemberService.php. Line : 510. Message : Call to a member function getYear() on null. [] []`

2020-02-28 12:59 UTC, PaulGOUX27 approved these changes

2020-02-28 12:59 UTC, merged