Feature/member
ETICINSATechnologies/Keros-Back pull request #24
Opened 2018-10-14 15:15 UTC by laurenttainturier

2018-10-14 17:42 UTC, ConorRyan requested changes

2018-10-14 17:42 UTC, ConorRyan commented on src/Controllers/Core/MemberController.php
> +        $this->logger->info($addressId);
Tu peux virer ce log, c'est bizarre de logger l'addresse id et pas le départ ID. A ta place je mettrais rien, mais si jamais tu veux faire un log comme ça, utiliser `->debug($msg)`pour dire que c'est pas important du tout

2018-10-14 17:42 UTC, ConorRyan commented on src/Controllers/Core/UserController.php
> +        $expiresAt = new DateTime("now");
Devrait être null. Sinon ça voudrait dire "Ca expire maintenant" aha

2018-10-14 17:42 UTC, ConorRyan commented on src/Entities/Core/Member.php
> +            'positionId' => []
positionId*s* , très important d'avoir tout ça à la letter près

2018-10-14 17:42 UTC, ConorRyan commented on src/Entities/Core/Member.php
> +        return ['username'];
tu peux mettre first name, last name, email aussi au moins

2018-10-14 17:42 UTC, ConorRyan commented on src/KerosApp.php
> +        $app = new \Slim\App(['settings' => ['displayErrorDetails' => true]]);
je pense que tu as fait un test de config c'est ça ? Faudrait remettre le config loader, si t'as des trucs à ajouter dans le config loader, comme `displayErrorDetails`, vas-y 😄

2018-10-14 17:42 UTC, ConorRyan commented on src/Services/Core/UserService.php
> +        }
Va falloir qu'on se fixe un style ! Mais OK

2018-10-14 17:42 UTC, ConorRyan commented on src/Tools/Logger.php
> +        $logger->pushHandler(new StreamHandler('php://stdout', \Monolog\Logger::INFO));
Ce INFO / DEBUG détermine le niveau minimal qui va être loggé. En local, c'est mieux de laisser DEBUG pour avoir le plus d'infos possible. Sur le serveur, on changera ça (faudra mettre ça dans settings.ini 😄 )

2018-10-14 17:42 UTC, ConorRyan commented on src/Tools/Validator.php
> +        if ($name == null)
Ce serait mieux, si c'est aussi facile, de garder à null et de "stocker" null dans la base de données. C'est plus facile à gérer par la suite et au front. S'il y a une bonne raison de le remplacer par une chaine vide, OK

2018-10-14 17:42 UTC, ConorRyan commented on src/Tools/Validator.php
> +        if ($bool == null)
OK ici par contre :)

2018-10-14 17:42 UTC, ConorRyan commented on src/Tools/Validator.php
> +                if (preg_match("/\d{2}:\d{2}:\d{2}$/", $date))
J'avais remarqué un ou deux pb avec ça, chapeau

2018-10-14 17:42 UTC, ConorRyan commented on src/Tools/Validator.php
> +        return $date == null || strlen($date) == 0 ? new DateTime("now") : self::date($date);
Là il faut vraiment laisser null par contre. Il y a une grosse différence entre null et now (comme par exemple date d'expiration, si on n'en a pas c'est null, plutôt que "déjà expiré")

2018-10-14 17:42 UTC, ConorRyan commented on src/Tools/Validator.php
> +        if ($telephone == null || strlen($telephone) == 0)
Parfait

2018-10-14 20:26 UTC, laurenttainturier commented on src/Services/Core/UserService.php
> +        }
J'ai fait Ctr+Alt+L donc tu me dis :-D

2018-10-20 14:30 UTC, ConorRyan approved these changes

2018-10-20 14:42 UTC, merged