Feature/encrypted password
ETICINSATechnologies/Keros-Back pull request #29
Opened 2018-10-30 08:27 UTC by laurenttainturier

2018-10-30 12:31 UTC, ConorRyan requested changes

2018-10-30 12:31 UTC, ConorRyan commented on src/KerosApp.php
> +                $this->get("/password", function (Request $request, Response $response, array $args) {
C'est du débug j'imagine ? A enlever maintenant, tout est OK sinon

2018-10-30 13:47 UTC, laurenttainturier commented on src/KerosApp.php
> +                $this->get("/password", function (Request $request, Response $response, array $args) {
Exact

2018-10-31 00:46 UTC, ConorRyan approved these changes

2018-10-31 00:46 UTC, merged