Feature/contact
ETICINSATechnologies/Keros-Back pull request #35
Opened 2018-11-09 13:45 UTC by laurenttainturier

2018-11-09 14:21 UTC, ConorRyan requested changes

2018-11-09 14:21 UTC, ConorRyan commented on src/Services/Ua/ContactService.php
> +        //$telephone = Validator::optionalPhone($fields["telephone"]);
Virer

2018-11-09 14:21 UTC, ConorRyan commented on src/Services/Ua/ContactService.php
> +            $old = Validator::requiredBool($fields["old"]);
Très bien, juste vérifie que c'est bien a "faux" par défaut dans la base si tu set pas, et pas a null

2018-11-09 14:21 UTC, ConorRyan commented on tests/Ua/ContactIntegrationTest.php
> +        $this->assertEquals($body->firstName, "Alexandre");
Arf, Il me semble que le premier paramètre est "expected" et 2iem "actual". Dear pas grave mais faites attention dan après, sinon les messages d'erreur sont moins clair

2018-11-10 09:43 UTC, laurenttainturier commented on src/Services/Ua/ContactService.php
> +            $old = Validator::requiredBool($fields["old"]);
Ce que j'ai fait c'est, lors de la création d'un contact, le bool est initialisé à faux et peut ensuite être modifié avec ces lignes de code

2018-11-10 09:46 UTC, laurenttainturier commented on tests/Ua/ContactIntegrationTest.php
> +        $this->assertEquals($body->firstName, "Alexandre");
Corrigé !

2018-11-10 10:35 UTC, ConorRyan approved these changes

2018-11-10 10:35 UTC, merged