Feature/delete study
ETICINSATechnologies/Keros-Back pull request #42
Opened 2018-12-16 21:57 UTC by Arteox

Feature delete study done

2018-12-18 16:43 UTC, laurenttainturier requested changes
Beau travail ! Je t'ai laissé quelques commentaires de détail et juste aussi tu peux rajouter un petit test( cf mon commentaire plus bas)

2018-12-18 16:43 UTC, laurenttainturier commented on src/DataServices/Ua/FieldDataService.php
> +        echo("deleted field");
Tu peux supprimer la ligne de debug

2018-12-18 16:43 UTC, laurenttainturier commented on src/DataServices/Ua/ProvenanceDataService.php
>          try {
Supprime les lignes vides dans la fonction.
Par contre tu peux rajouter un retour à la ligne après la fin de la fonction.

2018-12-18 16:43 UTC, laurenttainturier commented on src/DataServices/Ua/StatusDataService.php
> +    }
Même chose ici (retour à la ligne et debug)

2018-12-18 16:43 UTC, laurenttainturier commented on src/DataServices/Ua/StudyDataService.php
> +    }
Retour à la ligne

2018-12-18 16:43 UTC, laurenttainturier commented on src/Services/Ua/StudyService.php
> +
C'est du debug j'imagine ?

2018-12-18 16:43 UTC, laurenttainturier commented on tests/Ua/StudyIntegrationTest.php
>      {
Tu peux rajouter un test `testDeleteStudyShouldReturn404` où tu regardes ce qui se passe si l'étude n'existe pas ou qu'elle a déjà été supprimée.

2018-12-19 23:04 UTC, Arteox commented on src/Services/Ua/StudyService.php
> +
Oui c'est inutile je viens de le supprimer.

2018-12-19 23:04 UTC, Arteox commented on tests/Ua/StudyIntegrationTest.php
>      {
C'est fait !

2018-12-19 23:36 UTC, Marah232 approved these changes

2018-12-21 10:47 UTC, laurenttainturier approved these changes

2018-12-21 10:47 UTC, merged