Feature/template
ETICINSATechnologies/Keros-Back pull request #65
Opened 2019-02-12 18:23 UTC by PaulGOUX27

Elle est là !

2019-02-12 21:37 UTC, ConorRyan requested changes

2019-02-12 21:37 UTC, ConorRyan commented on .deploy/.travis.settings.ini
> +BACK_URL = http://keros-api-dev.etic-insa.com
tu peux mettre ça dans [application] comme on est déjà dans le back :)

2019-02-12 21:37 UTC, ConorRyan commented on src/Controllers/Core/TemplateController.php
> +    private function getStringGender(Gender $gender): string
Bien mais plutôt mettre ça dans Tools, n'apartient pas vraiment à un controlleur, et pourrais éventuellement être utilisé autre part

2019-02-12 21:37 UTC, ConorRyan commented on src/DataServices/DataServiceRegistrar.php
> -
Ce genre de diff est très dur à relire - à éviter dans le futur

2019-02-12 21:37 UTC, ConorRyan commented on src/Services/Core/TemplateService.php
> +        $templateType = $this->templateTypeService->getOne($typeId); //TODO $typeId
` //TODO $typeId` à enlever

2019-02-12 21:37 UTC, ConorRyan commented on src/Services/Core/TemplateService.php
> +        $typeId = Validator::requiredId($fields["typeId"]); //TODO
`// TODO` à enlever

2019-02-12 21:37 UTC, ConorRyan commented on src/Tools/Database/keros.sql
> +  `id` int(11) NOT NULL,
Me semble que le dernier commit de Laurent insère déjà ces tables et que tu peux enlever ces lignes (et à la limite modifier ses tables si besoin)

2019-02-12 21:37 UTC, ConorRyan commented on src/settings.ini
> +BACK_URL = http://keros-api-dev.etic-insa.com
Comme en haut : "tu peux mettre ça dans [application] comme on est déjà dans le back :)"

2019-02-12 21:37 UTC, ConorRyan commented on tests/Ua/StudyIntegrationTest.php
> +        $this->assertSame(500, $response->getStatusCode());
Ca devrait plutôt retourner 200 non aha ?

2019-02-12 21:37 UTC, ConorRyan commented on src/Controllers/Core/TemplateController.php
>              $contact->getPosition(),
vérifier que contact existe

2019-02-12 21:37 UTC, ConorRyan commented on src/Controllers/Core/TemplateController.php
> +        if ($gender->getLabel() == 'H')
Je trouve que switch { case M ; case F; default } est plus approprié, mais je chipote là aha

2019-02-12 21:37 UTC, ConorRyan commented on src/Controllers/Core/TemplateController.php
> +    private function getReplacementArray(Study $study, Member $connectedUser, array $consultants): array
vérifier que consultants non vide

2019-02-12 21:37 UTC, ConorRyan commented on src/Controllers/Core/TemplateController.php
> +            if (++$nbConsultant !== count($study->getConsultantsArray()))
"++$nbConsultant !== count($study->getConsultantsArray()" tu facilite pas la lecture aha

2019-02-12 22:01 UTC, PaulGOUX27 commented on tests/Ua/StudyIntegrationTest.php
> +        $this->assertSame(500, $response->getStatusCode());
La study 1 n'est pas valide (aucun consultant, cf trello). Je renvoie donc un code 500. 400 est peut être mieux, je ne sais pas

2019-02-12 22:02 UTC, PaulGOUX27 commented on tests/Ua/StudyIntegrationTest.php
> +        $this->assertSame(500, $response->getStatusCode());
La study 1 n'est pas valide (pas de consultant, cf trello). Plutôt retourner 400 ?

2019-02-13 00:50 UTC, ConorRyan approved these changes

2019-02-13 00:50 UTC, merged