Feature/document
ETICINSATechnologies/Keros-Back pull request #73
Opened 2019-02-26 17:00 UTC by PaulGOUX27

upload/download des documents version final

2019-02-26 17:16 UTC, Marah232 commented on src/Entities/Core/Document.php
> +    /** @Column(type="string", length=256) */
```suggestion
    /** @Column(type="string", length=255) */
```

2019-02-26 17:16 UTC, Marah232 commented on src/Entities/Core/Document.php
> +    /** @Column(type="string", length=256) */
```suggestion
    /** @Column(type="string", length=255) */
```

2019-02-26 18:15 UTC, Marah232 approved these changes

2019-03-16 16:54 UTC, ConorRyan requested changes
Toute la logique m'a l'air bon, juste quelques problèmes de versionnage/nettoyage

2019-03-16 16:54 UTC, ConorRyan commented on src/Controllers/Core/DocumentController.php
> +            $msg = 'No file given ' . json_encode($request->getUploadedFiles());
J'enlèverai le ` json_encode($request->getUploadedFiles());` - dans ce if ce sera toujours null de toute façon

2019-03-16 16:54 UTC, ConorRyan commented on src/Controllers/Core/DocumentController.php
> +        $this->logger->info($this->kerosConfig['STUDY_DOCUMENT_DIRECTORY'] . $document->getLocation());
A enlever. Ou du moins le mettre en "debug"

2019-03-16 16:54 UTC, ConorRyan commented on src/Entities/Core/Document.php
> +class Document implements JsonSerializable
Je pense que "StudyDocument" serait plus approprié - il y en aura d'autre qui ne sont pas rattachés à des study et donc l'attribut  $study posera problème sinon

2019-03-16 16:54 UTC, ConorRyan commented on src/Entities/Core/Document.php
> + * @Table(name="core_document")
Voir commentaire ci-dessous. Renomer. Je trouve que 'ua_study_document' serait mieux

2019-03-16 16:54 UTC, ConorRyan commented on src/Tools/Database/keros.sql
> +  (8, 'Treso', 'Trésorerie'),
Quand l'autoformattage se passe mal :)

Revert ce fichier comme c'était avant et formatte ton nouveau SQL dans un autre fichier avant de le mettre ici peut-être. Faut éviter ce genre de diff pour pas provoquer des conflits

2019-03-16 16:54 UTC, ConorRyan commented on src/Tools/ToolRegistrar.php
> +        $container[Logger::class] = function () {
Idem, évite de formatter tout le fichier

2019-03-16 16:54 UTC, ConorRyan commented on src/settings.ini
> +TEMPLATE_DIRECTORY = ../documents/templates/
Idem, évite de formatter tout le fichier

2019-03-16 17:51 UTC, ConorRyan approved these changes

2019-03-16 17:51 UTC, merged