Feature/main member
ETICINSATechnologies/Keros-Back pull request #85
Opened 2019-04-26 14:01 UTC by Arteox

2019-04-29 18:00 UTC, ConorRyan requested changes
Il faudra aussi rebase pour chopper les changements plus récents (tu devrais commencer par ça d'ailleurs, pour éventuellement, fix le problème git que j'ai mis en com)

2019-04-29 18:00 UTC, ConorRyan commented on src/Controllers/Ua/StudyController.php
> +    //only works if the current user is a member
Ca peut pas trop marcher comme la dashboard appelle cette fonction. Il faudrait regarder si c'est un membre ou un consultant connecté et traiter différemment

2019-04-29 18:00 UTC, ConorRyan commented on src/DataServices/DataServiceRegistrar.php
> +        $container[TemplateDataService::class] = function ($container) {
Problème avec Git je pense

2019-04-29 18:00 UTC, ConorRyan commented on src/DataServices/Ua/ContactDataService.php
> +            $this->queryBuilder->addSelect('(CASE WHEN f.mainContact = c.id THEN 1 ELSE 0 END) AS HIDDEN mainSort');
Perso j'aurai ajouté un booléan à la liaison, mais pourquoi pas :)

2019-04-29 18:00 UTC, ConorRyan commented on src/Entities/Ua/Study.php
> +            $tmpValue = $qualityManagersArray[0];
Ca aurait été mieux de faire une deuxième MR pour les trucs principaux (1 MR consultant, 1 MR principaux), mais pas grave on fera avec  !

2019-04-29 18:03 UTC, Arteox commented
> Il faudra aussi rebase pour chopper les changements plus récents (tu devrais commencer par ça d'ailleurs, pour éventuellement, fix le problème git que j'ai mis en com)

J'ai déjà fait un rebase si tu regardes mon historique de commit

2019-05-02 17:08 UTC, Arteox commented on src/DataServices/DataServiceRegistrar.php
> +        $container[TemplateDataService::class] = function ($container) {
Corrigé

2019-05-02 17:09 UTC, Arteox commented on src/DataServices/Ua/ContactDataService.php
> +            $this->queryBuilder->addSelect('(CASE WHEN f.mainContact = c.id THEN 1 ELSE 0 END) AS HIDDEN mainSort');
Comment ça un booléen ? Je vois pas trop en SQL comment tu fais avec des booléens

2019-05-02 17:10 UTC, Arteox commented on src/Controllers/Ua/StudyController.php
> +    //only works if the current user is a member
Corrigé !

2019-05-10 15:34 UTC, PaulGOUX27 requested changes
Super travail, c'est énorme ce que t'as fait mdr. Pour moi y'a pas de gros soucis, juste quelques petits ajustements ;)

2019-05-10 15:34 UTC, PaulGOUX27 commented on src/Controllers/Ua/StudyController.php
> +            if ($member->getId() == $userId) {
Pourquoi ne pas plutôt faire `$member = $this->memberService->getOne($userId)` ? Idem pour la partie avec consultant.

2019-05-10 15:34 UTC, PaulGOUX27 commented on src/Controllers/Core/ConsultantController.php
> +    {
`getConnectedConsultant` et celle en dessous aussi mais c'est un détail

2019-05-10 15:34 UTC, PaulGOUX27 commented on src/Services/Ua/StudyService.php
> +        }*/
Supprimer le commentaire

2019-05-10 15:34 UTC, PaulGOUX27 commented on src/DataServices/DataServiceRegistrar.php
> +        };
`ConsultantDataService::class` est en double 😜

2019-05-10 15:34 UTC, PaulGOUX27 commented on src/Entities/Core/Consultant.php
> +    protected $company;
Je vois pas cet attribut dans la doc 🤔

2019-05-10 15:34 UTC, PaulGOUX27 commented on src/Entities/Ua/Study.php
> +    /** @Column(type="integer")*/
Tu peux mettre les deux commentaire ensemble 
```
/**
* The main leader's member ID
* @Column(type="integer")
*/
```

2019-05-10 15:34 UTC, PaulGOUX27 commented on src/Entities/Ua/Study.php
> +            'mainConsultant' => $this->getMainConsultant()
Je pense pas qu'on en ai besoin d'envoyer juste l'id des mains au front.

2019-05-10 15:34 UTC, PaulGOUX27 commented on src/Entities/Ua/Firm.php
> +            'mainContact' => $this->getMainContact(),
Je pense pas qu'on en ai besoin d'envoyer juste l'id du main contact au front, Si il est premier dans le tableau ça suffit ;)

2019-05-10 15:34 UTC, PaulGOUX27 commented on src/Services/Core/ConsultantService.php
> +        $telephone = Validator::optionalPhone(isset($fields["telephone"]) ? $fields["telephone"] : null);
Le numéro de téléphone, le département et schoolYear sont required.

2019-05-10 15:34 UTC, PaulGOUX27 commented on src/Services/Core/ConsultantService.php
> +        if (isset($departmentId)) {
Le département est aussi required, ce qui enlève le if en dessous.

2019-05-10 15:34 UTC, PaulGOUX27 commented on src/Services/Core/ConsultantService.php
> +        $company = Validator::optionalString($fields["company"]);
Comme dit avant, y'a pas de `company` dans la doc

2019-05-10 15:34 UTC, PaulGOUX27 commented on src/Services/Core/ConsultantService.php
> +    {
Même remarque à propos des required qu'avant 😉

2019-05-10 15:34 UTC, PaulGOUX27 commented on src/Services/Core/MemberService.php
> +    private $consultantService;
hmmm ... tu l'utilise ? 😄

2019-05-10 15:34 UTC, PaulGOUX27 commented on src/Tools/Database/kerosData.sql
> +  (2, '471245896', 'JetBrains', 5, 1, null);
Là c'est plus un problème conceptuel. Si on a un `mainContact` à null, l'ordre du tableau ne va pas changer, et le premier sera toujours considéré par le front comme étant principal. Je pense que ça pose de soucis, mais la question est intéressante à se poser.

2019-05-10 15:34 UTC, PaulGOUX27 commented on tests/Core/ConsultantIntegrationTest.php
> +    public function testSearchConsuShouldReturn200()
`testSearchConsultantShouldReturn200`

2019-05-15 17:24 UTC, Arteox commented on src/Controllers/Ua/StudyController.php
> +            if ($member->getId() == $userId) {
Ah ça c'est parce que si je trouve pas le membre ça me fait une erreur et ça interrompt tout...

2019-05-15 17:33 UTC, Arteox commented on src/Entities/Core/Consultant.php
> +    protected $company;
Je l'enlève !

2019-05-15 18:12 UTC, Arteox commented on src/Entities/Ua/Study.php
> +            'mainConsultant' => $this->getMainConsultant()
C'est corrigé

2019-05-15 18:16 UTC, Arteox commented on src/Entities/Core/Consultant.php
> +    protected $company;
On m'a dit que c'est un attribut rajouté par Laurent sans passer par la doc pour l'annuaire, du coup on garde a priori !

2019-05-15 18:46 UTC, Arteox commented on src/Services/Core/ConsultantService.php
> +        $company = Validator::optionalString($fields["company"]);
Après concertation avec Conor, je le laisse

2019-05-15 18:48 UTC, Arteox commented on src/Services/Core/MemberService.php
> +    private $consultantService;
Non pas du tout x)
Je l'ai enlevé c'est bon

2019-05-15 18:50 UTC, Arteox commented on src/Tools/Database/kerosData.sql
> +  (2, '471245896', 'JetBrains', 5, 1, null);
Je pense que c'est OK  comme ça pour l'instant
Si jamais ça pose soucis je corrigerai

2019-05-16 16:21 UTC, PaulGOUX27 requested changes
Juste une petite ligne que tu as supprimée alors qu'il fallait pas ^^

2019-05-16 16:21 UTC, PaulGOUX27 commented on src/Entities/Ua/Study.php
> -            'confidential' => $this->getConfidential(),
Il devrait rester lui non ?

2019-05-16 16:22 UTC, Arteox commented on src/Entities/Ua/Study.php
> -            'confidential' => $this->getConfidential(),
T'as raison oups !

2019-05-16 16:37 UTC, PaulGOUX27 approved these changes

2019-05-20 18:14 UTC, ConorRyan requested changes
Il y a aussi deux fichiers 
 tests/Ua/test.txt 
et  tests/test.txt  
vides à enlever du commit.
Je ne voyais pas l'implémentation de mainContact/mainMember comme ça, mais ça me parait bien en tous cas 👍 :) .
Idéalement décomposer ce travail en 3 pull request la prochaine fois.
1) Main member
2) Main contact
3) Ajout consultant.
Si c'est possible de le décomposer en plusieurs PR (que ça peut être fonctionnel avec chaque petit PR) c'est mieux !

2019-05-20 18:14 UTC, ConorRyan commented on src/Controllers/Ua/StudyController.php
> +        $consultants = $this->consultantService->getAll();
Pas assez optimisé selon moi. Faudrait utiliser le member service pour get un membre avec un id spécifique, et un consultant spécifique. Si c'est les erreurs qui genent, mieux de les catcher je pense.

2019-05-20 18:14 UTC, ConorRyan commented on src/Services/Core/MemberService.php
> +    public function getAll() : array
Ne devrait pas exister selon moi - si on a 2000 membres ça ira mettre en mémoire les 2000. Je pense que le mieux est de supprimer cette méthode ici et dans MemberDataService, car je pense qu'il n'y a aucun cas où elle est acceptable niveau performance.
Pour pallier ça, il faut passer les paramètres juqu'au SQL pour qu'il ne récupère que ce dont on a besoin

2019-05-20 18:15 UTC, ConorRyan commented on src/Services/Core/MemberService.php
> +    public function getAll() : array
Pareil pour consultant service et consultantDataService ausso !

2019-05-23 13:14 UTC, Arteox commented on src/Controllers/Ua/StudyController.php
> +        $consultants = $this->consultantService->getAll();
Ok j'ai fait un try catch

2019-05-23 13:16 UTC, Arteox commented on src/Services/Core/MemberService.php
> +    public function getAll() : array
En effet c'est bien pensé ! J'enlève ça

2019-06-02 12:52 UTC, ConorRyan approved these changes

2019-06-02 12:52 UTC, merged